export enum Pokemon_Types {
    STEEL = "Steel",
    COMBAT = "Combat",
    DRAGON = "Dragon",
    WATER = "Water",
    ELECTRICK = "Electrick",
    FAIRY = "Fairy",
    FIRE = "Fire",
    ICE = "Ice",
    BUG = "Bug",
    NORMAL = "Normal",
    GRASS = "Grass",
    POISON = "Poison",
    PSY = "Psy",
    ROCK = "Rock",
    GROUND = "Ground",
    GHOST = "Ghost",
    DARK = "Dark",
    FLY = "Fly",
    None = "None",
}